import { Database, Hash, FileText, Code, LucideIcon } from 'lucide-react';

export const conceptIcons: Record<string, { icon: LucideIcon; className: string }> = {
  "Dictionary Operations": {
    icon: Hash,
    className: "bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-900/20 dark:text-purple-400 dark:border-purple-800",
  },
  "String Manipulation": {
    icon: FileText,
    className: "bg-green-50 text-green-700 border-green-200 dark:bg-green-900/20 dark:text-green-400 dark:border-green-800",
  },
  "Array Manipulation": {
    icon: Database,
    className: "bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-900/20 dark:text-blue-400 dark:border-blue-800",
  },
  "List Operations": {
    icon: Database,
    className: "bg-blue-50 text-blue-700 border-blue-200 dark:bg-blue-900/20 dark:text-blue-400 dark:border-blue-800",
  },
  "Lambda Functions": {
    icon: Code,
    className: "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-900/20 dark:text-amber-400 dark:border-amber-800",
  },
  "Function Creation": {
    icon: Code,
    className: "bg-amber-50 text-amber-700 border-amber-200 dark:bg-amber-900/20 dark:text-amber-400 dark:border-amber-800",
  },
  "Property Decorators": {
    icon: Code,
    className: "bg-red-50 text-red-700 border-red-200 dark:bg-red-900/20 dark:text-red-400 dark:border-red-800",
  },
  "Dictionary Creation": {
    icon: Hash,
    className: "bg-purple-50 text-purple-700 border-purple-200 dark:bg-purple-900/20 dark:text-purple-400 dark:border-purple-800",
  },
};

export const dummyCards = [
  {
    id: "1",
    title: "SnapChat Message",
    thumbnail: "/assets/sessionThumbnails/sc1.png",
    createdAt: new Date("2025-05-01"),
    userImg: "/assets/images/jason.png",
    username: "Jason",
    views: 10,
    visibility: "public",
    duration: 156,
  },
  {
    id: "2",
    title: "Product Demo Walkthrough",
    thumbnail: "/assets/sessionThumbnails/sc2.png",
    createdAt: new Date("2025-04-15"),
    userImg: "/assets/images/sarah.png",
    username: "Sarah",
    views: 245,
    visibility: "public",
    duration: 320,
  },
  {
    id: "3",
    title: "Weekly Team Update",
    thumbnail: "/assets/sessionThumbnails/sc3.png",
    createdAt: new Date("2025-04-22"),
    userImg: "/assets/images/michael.png",
    username: "Michael",
    views: 78,
    visibility: "private",
    duration: 412,
  },
  {
    id: "4",
    title: "Bug Fix Explanation",
    thumbnail: "/assets/sessionThumbnails/sc4.png",
    createdAt: new Date("2025-04-28"),
    userImg: "/assets/images/emily.png",
    username: "Emily",
    views: 32,
    visibility: "public",
    duration: 183,
  },
  {
    id: "5",
    title: "New Feature Overview",
    thumbnail: "/assets/sessionThumbnails/sc5.png",
    createdAt: new Date("2025-05-05"),
    userImg: "/assets/images/david.png",
    username: "David",
    views: 156,
    visibility: "public",
    duration: 275,
  },
  {
    id: "6",
    title: "Client Presentation Feedback",
    thumbnail: "/assets/sessionThumbnails/sc6.png",
    createdAt: new Date("2025-05-10"),
    userImg: "/assets/images/lisa.png",
    username: "Lisa",
    views: 89,
    visibility: "private",
    duration: 198,
  },
  {
    id: "7",
    title: "UI Design Review",
    thumbnail: "/assets/sessionThumbnails/sc7.png",
    createdAt: new Date("2025-05-12"),
    userImg: "/assets/images/alex.png",
    username: "Alex",
    views: 124,
    visibility: "public",
    duration: 230,
  },
  {
    id: "8",
    title: "Marketing Strategy Discussion",
    thumbnail: "/assets/sessionThumbnails/sc8.png",
    createdAt: new Date("2025-05-18"),
    userImg: "/assets/images/jessica.png",
    username: "Jessica",
    views: 67,
    visibility: "public",
    duration: 345,
  }
]

export const emotionColors: Record<string, string> = {
 joy: "#ffd600",
 interest: "#8fd1c4",
 excitement: "#fff974",
 amusement: "#febf52",
 determination: "#ff5c00",
 concentration: "#336cff",
 calmness: "#a9cce1",
 satisfaction: "#a6ddaf",
 contentment: "#e5c6b4",
 confidence: "#9a4cb6",
 admiration: "#ffc58f",
 adoration: "#ffc6cc",
 aestheticAppreciation: "#e2cbff",
 anger: "#b21816",
 annoyance: "#5f6b7c",
 anxiety: "#6e42cc",
 awe: "#7dabd3",
 awkwardness: "#d7d99d",
 boredom: "#8f99a6",
 contemplation: "#b0aeef",
 confusion: "#c66a26",
 contempt: "#76842d",
 craving: "#54591c",
 disappointment: "#006c7c",
 disapproval: "#4e591a",
 disgust: "#1a7a41",
 distress: "#c5f264",
 doubt: "#998644",
 ecstasy: "#ff48a4",
 embarrassment: "#63c653",
 empathicPain: "#ca5555",
 enthusiasm: "#ff9142",
 entrancement: "#7554d6",
 envy: "#1d4921",
 fear: "#d1c9ef",
 gratitude: "#f0d3b6",
 guilt: "#879aa1",
 horror: "#772e7a",
 love: "#f44f4c",
 neutral: "#879aa1",
 nostalgia: "#b087a1",
 pain: "#8c1d1d",
 pride: "#9a4cb6",
 realization: "#217aa8",
 relief: "#fe927a",
 romance: "#f0cc86",
 sadness: "#305575",
 sarcasm: "#7f53a4",
 sexualDesire: "#aa0d59",
 shame: "#8a6262",
 surprise: "#70e63a",
 surpriseNegative: "#319d3f",
 surprisePositive: "#7affff",
 sympathy: "#7f88e0",
 tiredness: "#757575",
 triumph: "#ec8132"
}